// Prompts and parsing for generating challenges, mixed tests and exams with AI. The model writes
// the files; expected outputs are never trusted from the model: they are produced by running its
// reference solution (see aiAuthoring.ts). No vscode dependency so it can be unit-tested.

export type GenerationKind = 'challenge' | 'test';

export interface GenerationSpec {
  kind: GenerationKind;
  /** What the author asked for, in their own words. */
  request: string;
  /** Sidebar topic; "Tests" for mixed tests, undefined for Custom. */
  topic?: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  /** Language for the description and hints, e.g. "pt-br". */
  language: string;
  /** Titles that already exist, so the model picks something new. */
  existingTitles: string[];
}

export const CHALLENGE_FILES = ['challenge.json', 'description.md', 'Starter.java', 'Starter.classic.java', 'Solution.java', 'Solution.classic.java'] as const;
const REQUIRED_FILES = ['challenge.json', 'description.md', 'Starter.java', 'Solution.java'];

const FORMAT = `Answer with exactly these six files and nothing else, each one wrapped like this:

<<<FILE challenge.json>>>
...file content...
<<<END>>>

Files, in this order: challenge.json, description.md, Starter.java, Starter.classic.java, Solution.java, Solution.classic.java.
Do not use Markdown code fences around the files.`;

const CONVENTIONS = `How the platform works:
- The student's program reads everything from standard input and prints to standard output. It is graded by running it with each test's input and comparing the output exactly (trailing spaces and trailing blank lines are ignored). Programs run with a US locale, so "%.2f" prints a dot.
- Two Java styles are accepted, and every challenge ships both:
  - Modern (JDK 25+), in Starter.java and Solution.java: a compact source file with a top-level \`void main()\` and no class around it. Read input with \`IO.readln()\` (returns one line as a String, or null at the end) and print with \`IO.println(...)\` / \`IO.print(...)\`. Helper methods and records can be declared at the top level. java.util and the rest of java.base are imported automatically.
  - Classic, in Starter.classic.java and Solution.classic.java: \`import java.util.*;\` and \`public class Main { public static void main(String[] args) { ... } }\`, reading with \`Scanner\` and printing with \`System.out.println\`. Helper methods are \`static\`.
- The starters must compile, read the input like the solution does, and leave the real work as TODO comments. They must not contain the solution.
- The two solutions must be complete, correct and print exactly the same output for every input.

challenge.json (JSON, no comments):
{
  "title": "Short title",
  "topic": "TOPIC",
  "difficulty": "Easy" | "Medium" | "Hard",
  "hints": ["2 to 4 hints, from a gentle nudge to a specific pointer, never the full code"],
  "mustContain": [{ "pattern": "Java regex the code must match", "message": "Requirement shown to the student" }],
  "mustNotContain": [{ "pattern": "Java regex the code must not match", "message": "Shown when it matches" }],
  "tests": [{ "input": "exact stdin, every line ending in \\n" }, { "input": "...", "hidden": true }]
}
- Give 2 or 3 visible tests (shown to the student as examples) and 3 to 5 hidden tests for edge cases: zero, negative numbers, one element, boundaries, invalid choices.
- Do NOT write expected outputs. They are generated by running Solution.java.
- Rules are optional. Use at most 3, only for the concept being practised (for example a loop: "\\\\b(for|while)\\\\b"). Remember that backslashes are doubled inside JSON strings. The solutions must satisfy every rule.

description.md (Markdown): start with "# Title", then one or two sentences about the task, then **Input** (the exact input format), **Output** (the exact output format, with any messages written exactly), and **Things to know** (2 to 4 bullets about the Java features that help). Do not add an examples section: the platform shows the visible tests as examples automatically.`;

const TEST_RULES = `This is a "test": a bigger challenge that mixes several topics in one program, such as a console app with a menu. Requirements:
- Add "skills" to challenge.json: the topics the program combines, chosen from Variables, Conditionals, Loops, Data Structures, Strings, Methods, OOP and Streams. Pick 3 to 5.
- Prefer a menu-driven console app. The program prints its menu ONCE at the start (a "=== Name ===" line, then numbered options with "0. Exit"), then reads one option per line until "0". Options may read extra lines (values) right after the option line. Invalid options print "Invalid option". Option 0 prints "Goodbye!" and ends.
- In description.md, show the menu in a code block and describe every option in a table with the columns Option, Reads and Prints.
- Every test input is a whole session: a sequence of options and values that always ends with "0". Make the hidden sessions cover options used before any data exists, invalid options and values, exiting straight away, and a long session that uses every option.`;

export function buildGenerationPrompt(spec: GenerationSpec): { system: string; user: string } {
  const system = `You write programming exercises for beginners learning Java, for a VS Code extension in the style of HackerRank.

${CONVENTIONS.replace('"TOPIC"', JSON.stringify(spec.topic ?? 'Custom'))}
${spec.kind === 'test' ? `\n${TEST_RULES}\n` : ''}
Write the title, description.md, hints and rule messages in this language: ${spec.language}. Keep code identifiers, Java keywords and the program's printed messages in English unless the request says otherwise.

${FORMAT}`;

  const user = `Create one ${spec.kind === 'test' ? 'mixed test (menu-driven app)' : 'challenge'}.
Topic: ${spec.topic ?? 'none (custom)'}
Difficulty: ${spec.difficulty}
Request from the teacher: ${spec.request.trim() || '(no details: choose a good exercise for this topic and difficulty)'}
${spec.existingTitles.length ? `\nThese titles already exist, so make something different:\n${spec.existingTitles.slice(0, 80).map((t) => `- ${t}`).join('\n')}\n` : ''}`;
  return { system, user };
}

export function buildRepairPrompt(spec: GenerationSpec, files: Record<string, string>, problems: string[]): { system: string; user: string } {
  const { system } = buildGenerationPrompt(spec);
  const user = `You created these files, but checking them found problems.

${serializeFiles(files)}

Problems found by compiling and running the files:
${problems.map((p) => `- ${p.slice(0, 1500)}`).join('\n')}

Fix the problems and answer with all six files again, complete, in the same format. Keep what already works.`;
  return { system, user };
}

export function serializeFiles(files: Record<string, string>): string {
  return CHALLENGE_FILES.filter((f) => files[f] !== undefined)
    .map((f) => `<<<FILE ${f}>>>\n${files[f].replace(/\n$/, '')}\n<<<END>>>`)
    .join('\n\n');
}

/** Extracts the <<<FILE name>>> … <<<END>>> blocks from a model answer. */
export function parseFiles(text: string): { files: Record<string, string>; problems: string[] } {
  const files: Record<string, string> = {};
  const re = /<<<\s*FILE\s+([\w.]+)\s*>>>\s*\n([\s\S]*?)\n?\s*<<<\s*END\s*>>>/g;
  for (let m = re.exec(text); m; m = re.exec(text)) {
    const name = m[1];
    if ((CHALLENGE_FILES as readonly string[]).includes(name)) {
      // Some models wrap file content in a Markdown fence anyway.
      files[name] = m[2].replace(/^\s*```[\w.-]*\n/, '').replace(/\n```\s*$/, '').replace(/\s+$/, '') + '\n';
    }
  }
  const problems = REQUIRED_FILES.filter((f) => !files[f]).map((f) => `The answer is missing the file ${f}.`);
  return { files, problems };
}

export interface CleanChallengeJson {
  json: Record<string, unknown>;
  problems: string[];
}

/** Checks the model's challenge.json, keeps only known fields, and forces what the spec decides. */
export function cleanChallengeJson(text: string, spec: GenerationSpec, order: number): CleanChallengeJson {
  const problems: string[] = [];
  let raw: Record<string, unknown>;
  try {
    raw = JSON.parse(text.replace(/^﻿/, ''));
  } catch (e) {
    return { json: {}, problems: [`challenge.json is not valid JSON: ${(e as Error).message}`] };
  }
  const strings = (v: unknown) => (Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string' && x.trim() !== '') : []);
  const rules = (v: unknown, field: string) =>
    (Array.isArray(v) ? v : []).filter((r): r is { pattern: string; message: string } => {
      if (!r || typeof r.pattern !== 'string' || typeof r.message !== 'string') {
        return false;
      }
      try {
        new RegExp(r.pattern);
        return true;
      } catch {
        problems.push(`The ${field} pattern ${JSON.stringify(r.pattern)} is not a valid regular expression.`);
        return false;
      }
    }).map((r) => ({ pattern: r.pattern, message: r.message }));

  const tests = (Array.isArray(raw.tests) ? raw.tests : [])
    .filter((t): t is { input: string; hidden?: boolean } => !!t && typeof t.input === 'string')
    .map((t) => ({ input: t.input.endsWith('\n') || t.input === '' ? t.input : `${t.input}\n`, output: '', ...(t.hidden ? { hidden: true } : {}) }));
  const visible = tests.filter((t) => !t.hidden).length;
  if (tests.length < 3 || visible === 0) {
    problems.push(`challenge.json needs at least 3 tests with at least 1 visible (found ${tests.length} tests, ${visible} visible).`);
  }

  const title = typeof raw.title === 'string' && raw.title.trim() ? raw.title.trim() : '';
  if (!title) {
    problems.push('challenge.json has no "title".');
  }
  const json: Record<string, unknown> = {
    title,
    ...(spec.topic ? { topic: spec.topic } : {}),
    ...(spec.kind === 'test' ? { skills: strings(raw.skills).slice(0, 6) } : {}),
    difficulty: spec.difficulty,
    order,
    hints: strings(raw.hints).slice(0, 5),
    mustContain: rules(raw.mustContain, 'mustContain'),
    mustNotContain: rules(raw.mustNotContain, 'mustNotContain'),
    tests,
  };
  if (spec.kind === 'test' && (json.skills as string[]).length === 0) {
    json.skills = ['Variables', 'Conditionals', 'Loops'];
  }
  return { json, problems };
}

// ---------------------------------------------------------------- exams

export interface ExamPlanSpec {
  request: string;
  questions: number;
  language: string;
  /** Titles of existing challenges, which the plan may NOT reuse (questions are private). */
  existingTitles: string[];
}

export interface ExamPlan {
  title: string;
  description: string;
  questions: { title: string; brief: string; topic: string; difficulty: 'Easy' | 'Medium' | 'Hard'; kind: GenerationKind; points: number }[];
}

export function buildExamPlanPrompt(spec: ExamPlanSpec): { system: string; user: string } {
  const system = `You plan Java programming exams for beginners. An exam is a list of new, private coding questions, each graded automatically by running the student's program with stdin input and comparing its stdout.

Answer with JSON only, no Markdown fences:
{
  "title": "Exam title",
  "description": "One sentence about what the exam covers",
  "questions": [
    { "title": "Question title", "brief": "2 to 4 sentences describing exactly what the program reads and prints", "topic": "one of Variables, Conditionals, Loops, Data Structures, Strings, Methods, OOP, Streams, Tests", "difficulty": "Easy" | "Medium" | "Hard", "points": 10 to 50 }
  ]
}
- Order the questions from easiest to hardest, and make the points add up to 100.
- Use the topic "Tests" for a bigger menu-driven console app that mixes several topics. Use it for at most one question.
- Write the titles, brief and description in this language: ${spec.language}.`;
  const user = `Plan an exam with exactly ${spec.questions} questions.
What the exam should cover: ${spec.request.trim() || '(not specified: cover the basics of Java syntax)'}
${spec.existingTitles.length ? `\nDo not reuse these existing exercises:\n${spec.existingTitles.slice(0, 80).map((t) => `- ${t}`).join('\n')}\n` : ''}`;
  return { system, user };
}

/** Extracts and checks the exam plan JSON (tolerating fences or text around it). */
export function parseExamPlan(text: string, questions: number): { plan?: ExamPlan; problems: string[] } {
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  if (start === -1 || end <= start) {
    return { problems: ['The answer contains no JSON object.'] };
  }
  let raw: { title?: unknown; description?: unknown; questions?: unknown };
  try {
    raw = JSON.parse(text.slice(start, end + 1));
  } catch (e) {
    return { problems: [`The exam plan is not valid JSON: ${(e as Error).message}`] };
  }
  const levels = ['Easy', 'Medium', 'Hard'];
  const list = (Array.isArray(raw.questions) ? raw.questions : [])
    .filter((q) => q && typeof q.title === 'string' && typeof q.brief === 'string')
    .slice(0, questions)
    .map((q) => ({
      title: q.title.trim(),
      brief: q.brief.trim(),
      topic: typeof q.topic === 'string' && q.topic.trim() ? q.topic.trim() : 'Custom',
      difficulty: (levels.includes(q.difficulty) ? q.difficulty : 'Medium') as ExamPlan['questions'][number]['difficulty'],
      kind: (q.topic === 'Tests' ? 'test' : 'challenge') as GenerationKind,
      points: typeof q.points === 'number' && q.points > 0 ? Math.round(q.points) : Math.round(100 / questions),
    }));
  if (list.length === 0) {
    return { problems: ['The exam plan has no usable questions.'] };
  }
  return {
    plan: {
      title: typeof raw.title === 'string' && raw.title.trim() ? raw.title.trim() : 'AI Exam',
      description: typeof raw.description === 'string' ? raw.description.trim() : '',
      questions: list,
    },
    problems: [],
  };
}
